### ISSUE TITLE
Maven down?

### ISSUE THREAD

**Issue by clienthax** [TehNut-Mods/HWYLA#253]
#### Issue Description:
Unable to pull 
http://tehnut.info/maven/mcp/mobius/waila/Hwyla/1.8.20-B35_1.12/Hwyla-1.8.20-B35_1.12.pom
http://tehnut.info/maven/mcp/mobius/waila/Hwyla/1.8.20-B35_1.12/Hwyla-1.8.20-B35_1.12.jar

#### What happens:
Dependency is not found

#### What you expected to happen:
For it to be found

#### Steps to reproduce:

```
repositories {
    maven { url "http://tehnut.info/maven" }
}

dependencies {
    deobfCompile "mcp.mobius.waila:Hwyla:1.8.20-B35_1.12"
}
```

**Comment by TehNut** [comment]
Yes as noted on the homepage. You can pull from curse for now

**Comment by Boy132** [comment]
Could someone please give an example of how this needs to look?

**Comment by Kolbrandr** [comment]
I'd like to know how to pull it from curse as well

**Comment by TehNut** [comment]
You should (?) now be able to switch the maven endpoint to `https://maven.tehnut.info` to pull the following builds: 

![image](https://user-images.githubusercontent.com/5789439/85221211-d6ccbf00-b366-11ea-8d92-e3f3e984f2ce.png)

**Comment by Cydhra** [comment]
No, the server denies access with a 403: Forbidden error code:

https://maven.tehnut.info/mcp/mobius/waila/Hwyla/1.8.26-B41_1.12.2/Hwyla-1.8.26-B41_1.12.2.pom

**Comment by TehNut** [comment]
Whoops. Kids, don't play with CDN permissions at 3am. Should be available now.

**Comment by Cydhra** [comment]
confirmed with `1.8.26-B41_1.12.2`

**Comment by Edivad99** [comment]
confirmed with `Hwyla-1.10.8-B72_1.15.2`

**Comment by rubensworks** [comment]
Same here for 1.10.8-B72_1.15.2.

**Comment by ghost** [comment]
Trying to browse the maven repo still produces access denied for me. I'm only able to access the files with direct links.

Edit: Without being able to browse the maven repo, I had to guess that the url was https://maven.tehnut.info/mcp/mobius/waila/Hwyla/fabric-1.16.1-1.9.22-75/Hwyla-fabric-1.16.1-1.9.22-75.pom. It took me a bit of time to figure this out, but if anyone else needs the link for the latest version of Hywla as of this writing, here it is.

Edit 2: It appears the link I posted broke since I've posted it.

**Comment by TehNut** [comment]
That link never would have worked in the first place. The artifact does not include `-fabric` in the name. The correct URL for the latest Fabric build is https://maven.tehnut.info/mcp/mobius/waila/Hwyla/1.16.1-1.9.22-75/Hwyla-1.16.1-1.9.22-75.jar.

Also, it's a CDN. It's not supposed to be browseable. I'm working on a solution to that, but I haven't had time to put into it.

**Comment by ghost** [comment]
Yep, I must have copied the wrong link I was experimenting with. Looking at the POM I downloaded, I didn't have fabric in the name. Thanks!

[Hwyla-1.16.1-1.9.22-75.pom.renamed.for.github.txt](https://github.com/TehNut/HWYLA/files/4841825/Hwyla-1.16.1-1.9.22-75.pom.renamed.for.github.txt)

**Comment by Edivad99** [comment]
Why don't you load api on curseforge? At least you're sure they always work.

**Comment by ghost** [comment]
I'm trying to get Hywla to work in my development environment. That way I can work on adding support for Hywla in my mod. I'm trying to get Gradle to download it and remap the jar for the development environment.

Currently, Gradle refuses to even look at maven.tehnut.info even though it's in my repository list, so I'm not sure if remapping works for Hywla yet (I had successfully loaded TechReborn and Mod Menu using the same method I'm trying to load Hywla with).

Edit: I should mention, I'm trying to do this in a way so that anyone who clones the repo can perform the tests themselves without having to go through this setup again while at the same time not redistributing any 3rd party jars.

Edit 2: Here's a build scan. https://scans.gradle.com/s/xifzofky52nay

It appears that gradle is contacting the repo, but it stops before it gets to resolve Hywla. It is searching for eclipse dependencies for some reason on the repo. It gets 403 errors across the board, so my guess is it gives up?

**Comment by ghost** [comment]
So, I got the dependency to download. I just now need to figure out how to get the jar to be remapped so I can load it in the development environment. That is outside of the scope of this issue report, so I'll be leaving this issue alone now.

**Comment by shartte** [comment]
We are probably going to mirror the API artifact since everytime the Maven goes down, so does our build :-|

**Comment by BinaryQuantumSoul** [comment]
What's the good one for forge ? I used `mcp.mobius.waila:Hwyla:1.10.8-B72_1.15.2` but the docs say it's for fabric.

**Comment by puggan** [comment]
Is the readme-page getting an update?

**Comment by TehNut** [comment]
Yup, whenever I update it.

**Comment by ghost** [comment]
TehNut, in the meantime while you are working on fixing the Maven, can you post a dev jar to Curseforge which doesn't remap classes such as `Identifier` to `class_2960`? That would help greatly as then people can get the development jar directly from Curseforge by using https://github.com/Wyn-Price/CurseMaven.

Edit: I should also mention, having https://maven.tehnut.info/ greatly slows down Gradle's ability to process my builds. Loading gradle in debug mode shows that a lot of dependencies get 403'd even though this particular repo is in the bottom of my list of repos. Taking this Maven out makes Gradle work in seconds instead of the indeterminate amount of time it would have taken, plus I get no 403s (also taking out Hywla too of course). So, I'm looking for an alternative that doesn't spit out a bunch of 403s and works quickly. I believe the 403s slow Gradle down for some reason, maybe having to do with logging?

**Comment by TehNut** [comment]
But it *is* fixed. 

https://github.com/TehNut/HWYLA/issues/253#issuecomment-647103525

**Comment by ghost** [comment]
I should also mention, this Maven is the only one that goes out on me a lot too and looking at it in my browser shows that the site is inaccessible (which could be the other reason Gradle is so slow).

![Screen Shot 2020-07-07 at 7 56 43 PM](https://user-images.githubusercontent.com/6305346/86857219-0c261c00-c08c-11ea-9813-61bf626966b4.png)

**Comment by TehNut** [comment]
https://maven.tehnut.info/mcp/mobius/waila/Hwyla/1.8.26-B41_1.12.2/Hwyla-1.8.26-B41_1.12.2.pom is downloading the file properly for me. `maven.tehnut.info` is just a CNAME for `tehnut-mod-maven.sfo2.cdn.digitaloceanspaces.com`, which has not had an availability issue since [June 28th](https://status.digitalocean.com/incidents/2bj9tjvs67rf).

**Comment by TehNut** [comment]
The README now displays the proper methods of pulling Hwyla as a library.
