### ISSUE TITLE
crash: Unexpected error

### ISSUE THREAD

**Issue by smenes** [TehNut-Mods/HWYLA#32]
Hi 

http://pastebin.com/raw/bF6t6pEn

**Comment by TehNut** [comment]
Is it reproducable? What were you looking at?

"hi" and a log is nowhere near enough information.

**Comment by smenes** [comment]
sorry
It was when I use "Tinsel Garland" in Fairy Lights mod
It happen 2 time and I removed HWYLA from the server.

**Comment by TehNut** [comment]
After looking through the Fairy Lights Github, I can only assume the crash is on their end (if the crash is definitely being caused by the Garland). The line crashing is [here](https://github.com/TehNut/HWYLA/blob/1.10/src/main/java/mcp/mobius/waila/network/Message0x03EntRequest.java#L34). All that line is doing is getting the entities dimension. The entity has already been nullchecked at that point and there is no reason a null should be thrown later on.

Please report it to them.
