### ISSUE TITLE
Broken pipe (not sure if it's hwyla)

### ISSUE THREAD

**Issue by Eufranio** [TehNut-Mods/HWYLA#38]
#### What happens:
My server randomly disconnects everyone, with the following error: https://hastebin.com/xovaxujeha.rb
I don't really know steps to reproduce, cause I run a server, so it's impressive... And the only mod I found in the log is Hwyla

#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.1-B13_1.10.2.jar
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

#### Possible Conflicting Mods (Provide their version, as well)
Not sure what could conflict with Waile, but [here](http://www.technicpack.net/modpack/magibeta-pack.940049/mods) is my mod list. Hope you can help me 😄

**Comment by TehNut** [comment]
That's uh... Hrm. Right now the Waila packet system is this super outdated bundle of abstraction from 1.6.4 (before Forge provided SimpleImpl). This could possibly be an artifact of it's age.

I'm hesitant to rewrite it for SimpleImpl because it works right now through lots of black magic, though it should probably be done. I'll add it to my todo list so we can see if it fixes it.

I find it odd that this is the first time it's been reported, though. How often do these disconnects occur? Could you try removing Hwyla from the server and seeing if that stops them? Your players will still be able to connect and use it just fine, there will just be slightly limited functionality when it comes to TileEntities.

**Comment by Eufranio** [comment]
I removed HWYLA yesterday and that's why I'm reporting this here: the errors stopped. The players aren't disconnected anymore, and before, they were disconnected after 6~10 hours of server uptime. After this time, ALL players started being disconnected. I think it's an issue with HWYLA and 1.10 servers, and you haven't received issues related because right now there are only a few servers running complete packs (that includes hwyla)...

**Comment by TehNut** [comment]
>there are only a few servers running complete packs (that includes hwyla)

With the release of Sky Factory 3, I doubt this. Also, this would be an issue with any packs shipping Waila as well.

**Comment by Eufranio** [comment]
They're still new.

**Comment by Eufranio** [comment]
Yay!

**Comment by TehNut** [comment]
This release has been out for almost a week but it broke things as seen in #42. I was actually waiting for feedback from you before closing it.

**Comment by Eufranio** [comment]
I wasnt notified of the fix until you close the issue and github send a mail :X
