### ISSUE TITLE
[1.10.2] Mod Crop Integration Slightly 

### ISSUE THREAD

**Issue by oitsjustjose** [TehNut-Mods/HWYLA#59]
#### Issue Description:

Well, I know you guys fixed the "Cheese crops" bug caused by WAILA reporting the base meta-value of mods' crops. It seems as though this fix only works on the fully grown crop, and not any lesser growth stages.

#### What happens:

![2017-03-29_08 41 13](https://cloud.githubusercontent.com/assets/3887324/24454936/cba9dc50-145b-11e7-9584-5cfc0ce15f44.png)

#### What you expected to happen:

![2017-03-29_08 41 28](https://cloud.githubusercontent.com/assets/3887324/24454938/cd3f59aa-145b-11e7-805d-fa5489d3341c.png)

#### Steps to reproduce:

1. Install HWYLA
2. Install any other mod adding BlockCrop and dropping meta-valued items

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: 1.8.12-B26_1.10.2
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

#### Possible Conflicting Mods (Provide their version, as well)

Actually Additions: 1.10.2-r105

**Comment by TehNut** [comment]
Honestly there's not really anything I can do about this without a proper Plant/Seed API from Forge. `IPlantable` and `IGrowable` are useless and `getSeed()` and `getCrop()` are also useless since they return an `Item` instead of an `ItemStack`. 

Looking at AA, a meta value is being passed to the crop constructor and that's what's being used for `damageDropped`. When the crop isn't fully grown, [`0` is being returned](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/blocks/base/BlockPlant.java#L89) instead of the proper meta value. I assume that "Paper Cones" have a meta value of 0? Seems like more of an issue on their side.

**Comment by TehNut** [comment]
This option was removed in 2c028e266558ac1f017c1f5a23c9d24db95a2a1b
