### ISSUE TITLE
[1.8.19-B33_1.12] Memory leak issue

### ISSUE THREAD

**Issue by kreezxil** [TehNut-Mods/HWYLA#83]
While analyzing my dedicated server logs, I saw an entry that said to turn find memory leaks to activate a java parameter. I did that and it looks like HWYLA has an issue with leaking memory.

https://pastebin.com/mGMcmTF0

**Comment by TeknoKit** [comment]
I have the exact same issue and leak records on my server lately.

**Comment by TehNut** [comment]
I am fairly sure this is not an issue on my end. Nothing I do with packets is non-standard.

**Comment by TeknoKit** [comment]
This is most likely the case. Removing HWYLA just causes the leak records to point to an entirely unrelated mod in the same fashion. Testing older versions of forge did not change this, despite not having these warnings previously when using those versions. It's hard to tell what has causes this when it complains everything doing this hasn't changed since it began.

**Comment by TehNut** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4282
